# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cd00a2ac3f3d923c2a58dade83f5abee5ecaa5a3c653dfe7ac97f42eda7b2162f4ebbd49a687905198c0c349ec470f95e38be9473fc4db3bd456096915878d8

test:
  secret_key_base: 2565170360501310569fd7c065e15357527f3237657dedd35bdc02aa3a542c4832ce45b8dbc1326725ed545d0f06e83c088ce113b34066c271f0f4d53b08e88b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
